"""
Cache OpenAI text embeddings for Variant 3 training

This script:
1. Loads training data generated by variant3_create_training_data.py
2. Extracts unique questions
3. Calls OpenAI API to get embeddings
4. Caches embeddings to disk for fast training

Cost estimation: ~$0.02 per 1M tokens
- Assuming avg 15 tokens per question
- 5000 unique questions = 75k tokens = $0.0015
"""

import pickle
import numpy as np
from pathlib import Path
from typing import Dict
from tqdm import tqdm
import openai
import time

from qa_system.config import Config


def get_openai_embedding(text: str, model: str = "text-embedding-3-small") -> np.ndarray:
    """
    Get OpenAI text embedding for a single text.

    Args:
        text: Input text
        model: OpenAI embedding model

    Returns:
        Numpy array of embedding (1536-dim for text-embedding-3-small)
    """
    response = openai.embeddings.create(
        input=text,
        model=model
    )
    embedding = response.data[0].embedding
    return np.array(embedding, dtype=np.float32)


def cache_embeddings(
    texts: list[str],
    output_path: Path,
    model: str = "text-embedding-3-small",
    batch_size: int = 100
):
    """
    Cache embeddings for a list of texts.

    Args:
        texts: List of unique texts to embed
        output_path: Path to save embeddings
        model: OpenAI embedding model
        batch_size: Number of texts to process in one API call
    """
    print(f"\n[Caching embeddings]")
    print(f"   Model: {model}")
    print(f"   Total texts: {len(texts)}")
    print(f"   Batch size: {batch_size}")

    # Dictionary to store: {text: embedding_vector}
    embedding_cache = {}

    # Process in batches
    num_batches = (len(texts) + batch_size - 1) // batch_size

    for i in tqdm(range(0, len(texts), batch_size), desc="Fetching embeddings", total=num_batches):
        batch_texts = texts[i:i + batch_size]

        try:
            # Batch API call
            response = openai.embeddings.create(
                input=batch_texts,
                model=model
            )

            # Store embeddings
            for j, text in enumerate(batch_texts):
                embedding = response.data[j].embedding
                embedding_cache[text] = np.array(embedding, dtype=np.float32)

        except Exception as e:
            print(f"\nError processing batch {i // batch_size + 1}: {e}")
            print("Retrying in 5 seconds...")
            time.sleep(5)

            # Retry individual texts in this batch
            for text in batch_texts:
                if text not in embedding_cache:
                    try:
                        embedding = get_openai_embedding(text, model)
                        embedding_cache[text] = embedding
                        time.sleep(0.1)  # Rate limiting
                    except Exception as e2:
                        print(f"Failed to embed text: {text[:50]}... Error: {e2}")

    # Save to disk
    with open(output_path, 'wb') as f:
        pickle.dump(embedding_cache, f)

    print(f"   Embeddings cached to: {output_path}")
    print(f"   Successfully cached: {len(embedding_cache)} / {len(texts)}")

    # Verify embedding dimension
    sample_embedding = next(iter(embedding_cache.values()))
    print(f"   Embedding dimension: {len(sample_embedding)}")

    return embedding_cache


def estimate_cost(num_texts: int, avg_tokens_per_text: int = 15):
    """Estimate OpenAI API cost"""
    total_tokens = num_texts * avg_tokens_per_text
    cost = total_tokens * Config.COST_PER_EMBEDDING
    print(f"\n[Cost Estimation]")
    print(f"   Texts: {num_texts}")
    print(f"   Avg tokens per text: {avg_tokens_per_text}")
    print(f"   Total tokens: {total_tokens:,}")
    print(f"   Estimated cost: ${cost:.4f}")


def main():
    print("=" * 80)
    print("Variant 3: Cache OpenAI Text Embeddings for Training")
    print("=" * 80)

    # Set OpenAI API key
    if not Config.OPENAI_API_KEY:
        raise ValueError("OPENAI_API_KEY not found in environment variables")

    openai.api_key = Config.OPENAI_API_KEY

    # Load training data
    print("\n[1/4] Loading training data...")
    training_data_path = Config.BASE_DIR / "data" / "variant3_training_data.pkl"

    if not training_data_path.exists():
        raise FileNotFoundError(
            f"Training data not found at {training_data_path}\n"
            "Please run variant3_create_training_data.py first"
        )

    with open(training_data_path, 'rb') as f:
        training_samples = pickle.load(f)

    print(f"   Loaded {len(training_samples)} training samples")

    # Extract unique questions
    print("\n[2/4] Extracting unique questions...")
    unique_questions = sorted(set(s['question_text'] for s in training_samples))
    print(f"   Found {len(unique_questions)} unique questions")

    # Estimate cost
    estimate_cost(len(unique_questions))

    # Confirm before proceeding
    user_input = input("\nProceed with API calls? (yes/no): ")
    if user_input.lower() not in ['yes', 'y']:
        print("Aborted by user")
        return

    # Cache embeddings
    print("\n[3/4] Caching question embeddings...")
    output_path = Config.EMBEDDINGS_DIR / "variant3_question_embeddings_train.pkl"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    embedding_cache = cache_embeddings(
        texts=unique_questions,
        output_path=output_path,
        model=Config.OPENAI_MODEL_EMBED,
        batch_size=100  # OpenAI allows up to 2048 inputs per request
    )

    # Save list of questions in same order (for reference)
    print("\n[4/4] Saving question list...")
    question_list_path = Config.EMBEDDINGS_DIR / "variant3_question_list_train.pkl"
    with open(question_list_path, 'wb') as f:
        pickle.dump(unique_questions, f)

    print(f"   Question list saved to: {question_list_path}")

    print("\n" + "=" * 80)
    print("Embedding caching complete!")
    print("=" * 80)
    print(f"\nCached embeddings: {len(embedding_cache)}")
    print(f"Cache file: {output_path}")
    print(f"\nNext step: Run variant3_train_edge_scorer.py to train the model")


if __name__ == "__main__":
    main()
