"""
Cache ALL embeddings for Variant 3 Dual model training:
- Question text embeddings (OpenAI)
- Entity text embeddings (already generated by variant3_generate_text_embeddings.py)
- Relation text embeddings (already generated by variant3_generate_text_embeddings.py)

This script simply loads question training data and caches unique question embeddings.
Entity and relation embeddings are loaded from pre-generated files.

Cost estimation: ~$0.002 for unique questions (already estimated in variant3_generate_text_embeddings.py)
"""

import pickle
import numpy as np
from pathlib import Path
from typing import Dict
from tqdm import tqdm
import openai
import time

from qa_system.config import Config


def batch_embed_texts(
    texts: list[str],
    model: str = "text-embedding-3-small",
    batch_size: int = 2048  # OpenAI max batch size for faster processing
) -> Dict[str, np.ndarray]:
    """
    Batch embed texts using OpenAI API.

    Args:
        texts: List of text strings
        model: OpenAI embedding model
        batch_size: Number of texts per API call

    Returns:
        Dict mapping text -> embedding
    """
    embeddings = {}
    num_batches = (len(texts) + batch_size - 1) // batch_size

    for i in tqdm(range(0, len(texts), batch_size), desc="Fetching embeddings", total=num_batches):
        batch_texts = texts[i:i + batch_size]

        try:
            response = openai.embeddings.create(
                input=batch_texts,
                model=model
            )

            for j, text in enumerate(batch_texts):
                embedding = response.data[j].embedding
                embeddings[text] = np.array(embedding, dtype=np.float32)

        except Exception as e:
            print(f"\nError processing batch {i // batch_size + 1}: {e}")
            print("Retrying in 5 seconds...")
            time.sleep(5)

            # Retry individually
            for text in batch_texts:
                if text not in embeddings:
                    try:
                        response = openai.embeddings.create(input=[text], model=model)
                        embedding = response.data[0].embedding
                        embeddings[text] = np.array(embedding, dtype=np.float32)
                        time.sleep(0.1)
                    except Exception as e2:
                        print(f"Failed to embed: {text[:50]}... Error: {e2}")

        time.sleep(0.1)  # Rate limiting

    return embeddings


def main():
    print("=" * 80)
    print("Variant 3 Dual: Cache Question Embeddings for Training")
    print("=" * 80)

    # Set OpenAI API key
    if not Config.OPENAI_API_KEY:
        raise ValueError("OPENAI_API_KEY not found in environment variables")

    openai.api_key = Config.OPENAI_API_KEY

    # Load training data
    print("\n[1/4] Loading training data...")
    training_data_path = Config.BASE_DIR / "data" / "variant3_training_data.pkl"

    if not training_data_path.exists():
        raise FileNotFoundError(
            f"Training data not found at {training_data_path}\n"
            "Please run variant3_create_training_data.py first"
        )

    with open(training_data_path, 'rb') as f:
        training_samples = pickle.load(f)

    print(f"   Loaded {len(training_samples):,} training samples")

    # Extract unique questions
    print("\n[2/4] Extracting unique questions...")
    unique_questions = sorted(set(s['question_text'] for s in training_samples))
    print(f"   Found {len(unique_questions):,} unique questions")

    # Estimate cost
    avg_tokens = 15
    total_tokens = len(unique_questions) * avg_tokens
    cost = total_tokens * Config.COST_PER_EMBEDDING

    print(f"\n[Cost Estimation]")
    print(f"   Questions: {len(unique_questions):,}")
    print(f"   Avg tokens per question: {avg_tokens}")
    print(f"   Total tokens: {total_tokens:,}")
    print(f"   Estimated cost: ${cost:.4f}")

    # Confirm
    user_input = input("\nProceed with API calls? (yes/no): ")
    if user_input.lower() not in ['yes', 'y']:
        print("Aborted by user")
        return

    # Cache question embeddings
    print("\n[3/4] Caching question embeddings...")
    output_dir = Config.EMBEDDINGS_DIR
    output_dir.mkdir(parents=True, exist_ok=True)

    question_emb_path = output_dir / "variant3_question_embeddings_train.pkl"

    question_embeddings = batch_embed_texts(
        unique_questions,
        model=Config.OPENAI_MODEL_EMBED,
        batch_size=2048  # Use max batch size for faster processing
    )

    with open(question_emb_path, 'wb') as f:
        pickle.dump(question_embeddings, f)

    print(f"   Question embeddings saved: {question_emb_path}")
    print(f"   Cached: {len(question_embeddings):,} / {len(unique_questions):,}")

    # Verify all embeddings exist
    print("\n[4/4] Verifying all embeddings...")

    entity_emb_path = output_dir / "variant3_entity_text_embeddings.pkl"
    relation_emb_path = output_dir / "variant3_relation_text_embeddings.pkl"

    if not entity_emb_path.exists():
        print(f"\n   WARNING: Entity embeddings not found at {entity_emb_path}")
        print("   Please run variant3_generate_text_embeddings.py first")
        return

    if not relation_emb_path.exists():
        print(f"\n   WARNING: Relation embeddings not found at {relation_emb_path}")
        print("   Please run variant3_generate_text_embeddings.py first")
        return

    with open(entity_emb_path, 'rb') as f:
        entity_embeddings = pickle.load(f)

    with open(relation_emb_path, 'rb') as f:
        relation_embeddings = pickle.load(f)

    print(f"   ✓ Question embeddings: {len(question_embeddings):,}")
    print(f"   ✓ Entity embeddings: {len(entity_embeddings):,}")
    print(f"   ✓ Relation embeddings: {len(relation_embeddings):,}")

    # Verify dimensions
    sample_q = next(iter(question_embeddings.values()))
    sample_e = next(iter(entity_embeddings.values()))
    sample_r = next(iter(relation_embeddings.values()))

    print(f"\n   Embedding dimensions:")
    print(f"   Question: {sample_q.shape}")
    print(f"   Entity: {sample_e.shape}")
    print(f"   Relation: {sample_r.shape}")

    print("\n" + "=" * 80)
    print("Embedding caching complete!")
    print("=" * 80)
    print(f"\nAll embeddings ready for training:")
    print(f"   Questions: {question_emb_path}")
    print(f"   Entities: {entity_emb_path}")
    print(f"   Relations: {relation_emb_path}")
    print(f"\nNext step: Run variant3_train_edge_scorer_dual.py to train the model")


if __name__ == "__main__":
    main()